version: "3.9"

services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=arvan_lib
      - POSTGRES_USER=arvan_user
      - POSTGRES_PASSWORD=arvan_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data: