# Generated by Django 4.2.6 on 2023-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="s"),
            preserve_default=False,
        ),
    ]
