# Generated by Django 4.2.6 on 2023-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0002_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("isbn", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("d", "Deleted"),
                            ("b", "Borrowed"),
                            ("a", "Available"),
                        ],
                        default="a",
                        max_length=1,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="books", to="category.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
