# Generated by Django 4.2.6 on 2023-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bookgallery_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgallery",
            name="image_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
